// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfuroouzxmxlvkwsmtny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmdXJvb3V6eG14bHZrd3NtdG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDA5MTgsImV4cCI6MjA3MjExNjkxOH0.aIjVvQ24fIS1unfm0yP3y2jXuNwe_8X2xGHgl0y5ax8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});